import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const script = await readFile(new URL("../scripts/dungeon-masters-forge.js", import.meta.url), "utf8");
const forgeEngine = await readFile(new URL("../scripts/forge-engine.js", import.meta.url), "utf8");
const styles = await readFile(new URL("../styles/dungeon-masters-forge.css", import.meta.url), "utf8");
const settingsTemplate = await readFile(new URL("../templates/forge-settings.hbs", import.meta.url), "utf8");

assert.match(script, /aria-live="polite"/);
assert.match(script, /function bindForgeUsability\(/);
assert.match(script, /game\.settings\.registerMenu\(MODULE_ID, "forgeSettings"/);
assert.match(script, /approval\.addEventListener\("change"/);
assert.match(script, /specs\.addEventListener\("input"/);
assert.doesNotMatch(script, /action: "close"/);
assert.match(styles, /\.dm_forge-panel[\s\S]*overflow-y: auto/);
assert.match(styles, /\.dm_forge-workflow[\s\S]*grid-template-columns: minmax\(0, 0\.95fr\) minmax\(0, 1\.05fr\)/);
assert.match(styles, /\.dungeon-masters-forge \.form-footer \[data-action="create"\][\s\S]*margin-left: auto/);
assert.match(styles, /button\.dm_forge-create:disabled/);
assert.match(styles, /\.dm_forge-request[\s\S]*flex: 1 1 auto/);
assert.match(script, /buildReviewSummaries/);
assert.match(script, /class="dm_forge-review-summary"/);
assert.match(script, /data-forge-panel="request"/);
assert.match(script, /data-forge-panel="review"/);
assert.match(script, /<span>Description<\/span>/);
assert.match(script, /<span>Result<\/span>/);
assert.match(styles, /\.dm_forge-pane-header/);
assert.match(styles, /\.dm_forge-provider-summary/);
assert.match(styles, /\.dm_forge-settings-shell \.form-header/);
assert.match(styles, /\.dm_forge-settings-intro-block[\s\S]*flex: 0 0 auto !important/);
assert.match(styles, /\.dm_forge-settings-shell > \.form-footer/);
assert.match(styles, /\.dm_forge-provider-settings[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(settingsTemplate, /class="dm_forge-settings-intro-block"/);
assert.match(script, /hideVerificationHarnessUtilities: true/);
assert.match(settingsTemplate, /#unless hideVerificationHarnessUtilities/);
assert.match(settingsTemplate, /class="dm_forge-provider-settings" data-provider-configuration/);
assert.match(script, /<details class="dm_forge-advanced">/);
assert.match(styles, /\.dm_forge-item-summary/);
assert.match(styles, /\.dm_forge-item-sheet-tabs/);
assert.match(styles, /\.dm_forge-bottom-tray/);
assert.match(script, /data-forge-notices/);
assert.match(script, /label: "Free Forge", states: \["free-forge"\]/);
assert.match(script, /label: "Notices", states: \["notice"\]/);
assert.match(script, /label: "Notes", states: \["assumption", "reference", "note"\]/);
assert.match(script, /return collectFooterNotes\(summaries, validation\);/);
assert.match(script, /const attentionCount = reviewGroups\.find\(group => group\.state === "warning"\)/);
assert.match(script, /function renderCompilationReport\(dialog, compilation, reviewNotes = null\)/);
assert.match(script, /const freeForgeCount = reviewGroup\("free-forge"\)\?\.notes\.length \?\? 0;/);
assert.match(script, /const noteCount = reviewGroup\("note"\)\?\.notes\.length \?\? 0;/);
assert.match(script, /<span>Free Forge \$\{freeForgeCount\}<\/span>/);
assert.match(script, /<span>Notes \$\{noteCount\}<\/span>/);
assert.match(styles, /\.dm_forge-footer-badge\[data-state="free-forge"\]/);
assert.match(styles, /\.dm_forge-footer-notes[\s\S]*max-height: min\(44vh, 420px\)[\s\S]*overflow-y: auto/);
assert.match(forgeEngine, /function patchWeaponBaseAttack\([\s\S]*spec\.conditionOnHit[\s\S]*macroData[\s\S]*conditionMacroCommand\(spec\)/);
assert.match(forgeEngine, /conditionHook[\s\S]*flags\.midi-qol\.onUseMacroName/);
assert.match(forgeEngine, /function buildWeaponBaseAttackData\([\s\S]*conditionMacroCommand\(spec\)[\s\S]*applyMidiQolActivityDefaults/);
assert.match(forgeEngine, /async function createArtifactWeaponHybrid\([\s\S]*buildWeaponBaseAttackData\(attack, spec\)[\s\S]*conditionOnHitHookUpdate/);
assert.match(styles, /border: 1px solid rgb\(69 214 204 \/ 24%\)/);
assert.match(script, /Report Failed Item/);
assert.match(script, /failedItemReportDialogContent/);
assert.match(script, /buildFailedItemReportPayload/);
assert.match(script, /data-action="report-failed-item"/);
assert.match(script, /Desired outcome in plain language/);
assert.match(script, /name="desiredOutcome"/);
assert.match(script, /name="reportConsent"/);
assert.match(script, /I understand that this report sends the prompt, generated specifications/);
assert.match(script, /name="automationCodeApproval"/);
assert.match(script, /Generated automation code/);
assert.match(script, /function renderAutomationCodeReview\(/);
assert.match(script, /data-forge-review-tab="visual"/);
assert.match(script, /data-forge-review-tab="automation"/);
assert.match(script, /function setReviewTab\(/);
assert.match(script, /Generated automation code approval is required before creation/);
assert.match(forgeEngine, /function generatedAutomationCode\(/);
assert.match(forgeEngine, /const automationCodePreview = generatedAutomationCode\(preparedItems\)/);
assert.match(forgeEngine, /automationCodePreview\n    \};/);
assert.match(forgeEngine, /authorizeGeneratedAutomation !== true/);
assert.match(script, /authorizeGeneratedAutomation: automationApproved/);
assert.match(script, /authorizeGeneratedAutomation: true/);
assert.match(script, /data-forge-footer-provider-status/);
assert.match(script, /_dm_forgeReviewValidated/);
assert.match(settingsTemplate, /name="providerEndpoint"/);
assert.match(settingsTemplate, /name="providerModel"/);
assert.match(settingsTemplate, /name="providerApiToken"/);
assert.match(settingsTemplate, /class="dm_forge-secret-input"/);
assert.match(settingsTemplate, /type="password"[^>]*name="providerApiToken"/);
assert.match(settingsTemplate, /name="providerApiToken"[^>]*autocomplete="new-password"/);
assert.match(settingsTemplate, /data-form-type="other"/);
assert.match(settingsTemplate, /name="itemFolderName"/);
assert.match(settingsTemplate, /name="actorFolderName"/);
assert.match(settingsTemplate, /name="replaceExisting"/);
assert.match(settingsTemplate, /name="enableVerificationHarness"/);
assert.match(settingsTemplate, /name="verificationWorldId"/);
assert.match(settingsTemplate, /data-action="setup-verification-harness"/);
assert.match(settingsTemplate, /name="rememberProviderApiToken"/);
assert.match(settingsTemplate, /name="anonymousErrorReports"/);
assert.match(settingsTemplate, /data-action="example"/);
assert.match(settingsTemplate, /data-action="diagnostics"/);
assert.match(script, /providerSessionConfiguration/);
assert.match(script, /syncSettingsProviderPanel/);
assert.match(settingsTemplate, /data-action="check-provider"/);
assert.match(settingsTemplate, /type="submit" data-action="save-settings"/);
assert.match(settingsTemplate, /data-action="open-forge"/);
assert.match(script, /requestRemoteHealth/);
assert.match(script, /requestRemoteServiceStatus/);
assert.match(script, /Checking remote service status/);
assert.match(script, /providerConnectionDetailText/);
assert.match(script, /action: "settings"/);
assert.match(styles, /\.dungeon-masters-forge \.form-footer \[data-action="settings"\]/);
assert.match(script, /async function prepareSpecsForForge\(input, requestText = ""\)/);
assert.match(script, /function currentVerificationHarnessOptions\(overrides = \{\}\)/);
assert.match(script, /setupIsolatedVerificationHarness/);
assert.match(script, /runIsolatedVerificationHarness/);
assert.match(script, /function syncPreparedSpecs\(dialog, form, specs\)/);
assert.match(script, /const preparedCompilation = compilationWithPreparedSpecs\(compilation, validation\.specs\);/);
assert.match(script, /const preparedRawSpecs = syncPreparedSpecs\(dialog, button\.form, validation\.specs\);/);
assert.ok((script.match(/const specs = await prepareSpecsForForge\(input, requestText\);/g) ?? []).length >= 2);
assert.doesNotMatch(script, /dungeonMastersForgeSettings/);
assert.match(script, /const form = root instanceof HTMLFormElement \? root : root\?\.querySelector\?\.\("form"\)/);
assert.ok((script.match(/const form = root instanceof HTMLFormElement \? root : root\?\.querySelector\?\.\("form"\)/g) ?? []).length >= 3);
assert.match(script, /mock mode/);
assert.match(script, /const storedApiToken = rememberApiToken/);
assert.match(script, /partitioned\.session\.apiToken \|\| storedApiToken/);
assert.match(script, /currentProviderToken\(\{ rememberProviderToken: true \}\)/);
assert.match(settingsTemplate, /Use only on a trusted computer/);
assert.match(styles, /\.dm_forge-secret-input[\s\S]*-webkit-text-security: disc/);
assert.match(script, /this\._dm_forgeProviderConnection = await checkProviderConnection\(providerState\);\s*await persistProviderState\(providerState\);/);
assert.match(script, /function applyHostedDefaultProvider\(\)/);
assert.match(script, /networkProviderConfiguration/);
assert.match(styles, /\.dm_forge-approval-box/);
assert.match(styles, /\.dm_forge-approval input:checked \+ \.dm_forge-approval-box/);
assert.match(script, /dm_forge-approval-compact/);
assert.match(styles, /\.dm_forge-report-action/);
assert.match(script, /relocateBottomActions/);
assert.match(styles, /\.dm_forge-actions-footer/);
assert.match(styles, /\.dm_forge-report-dialog/);
assert.match(script, /minimizable: true/);
assert.match(script, /const mechanicsRequest = mechanicsRequestForCompilation\(compilation, requestText\);/);
assert.match(script, /const validation = await validateSpecs\(compilation\.specs, mechanicsRequest\);/);
assert.match(script, /preserveExistingWhenUnspecified: true/);
assert.match(script, /needs\?\|requires\?\|requiring/);
assert.match(script, /async function createPreparedSpecs\(specs, configOverrides = \{\}\)/);
assert.match(script, /const result = await createPreparedSpecs\(validation\.specs, \{/);
assert.match(styles, /\.dm_forge-settings-shell > \.form-footer button[\s\S]*color: #f6ebe2/);
assert.match(forgeEngine, /function compactText\(value\)/);
assert.match(forgeEngine, /override: Boolean\(hasExplicitRange \|\| range\.override === true\)/);
assert.match(forgeEngine, /override: Boolean\(hasTemplate \|\| hasAffects \|\| target\?\.override === true\)/);
assert.match(forgeEngine, /function activityConsumption\(chargeCost = 1, scaling = \{\}\)[\s\S]*spellSlot: false/);
assert.match(forgeEngine, /function activityConsumptionNone\(\)[\s\S]*spellSlot: false/);
assert.doesNotMatch(script, /planningTier/);
assert.doesNotMatch(script, /tierReview/);
assert.doesNotMatch(settingsTemplate, /Planning tier/);

export const testedUsabilityContractCount = 96;
