import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const script = await readFile(new URL("../scripts/dungeon-masters-forge.js", import.meta.url), "utf8");
const forgeEngine = await readFile(new URL("../scripts/forge-engine.js", import.meta.url), "utf8");
const styles = await readFile(new URL("../styles/dungeon-masters-forge.css", import.meta.url), "utf8");
const settingsTemplate = await readFile(new URL("../templates/forge-settings.hbs", import.meta.url), "utf8");

assert.match(script, /aria-live="polite"/);
assert.match(script, /function bindForgeUsability\(/);
assert.match(script, /game\.settings\.registerMenu\(MODULE_ID, "forgeSettings"/);
assert.match(script, /approval\.addEventListener\("change"/);
assert.match(script, /specs\.addEventListener\("input"/);
assert.doesNotMatch(script, /action: "close"/);
assert.match(styles, /\.dm_forge-panel[\s\S]*overflow-y: auto/);
assert.match(styles, /\.dm_forge-workflow[\s\S]*grid-template-columns: minmax\(0, 0\.95fr\) minmax\(0, 1\.05fr\)/);
assert.match(styles, /\.dungeon-masters-forge \.form-footer \[data-action="create"\][\s\S]*margin-left: auto/);
assert.match(styles, /button\.dm_forge-create:disabled/);
assert.match(styles, /\.dm_forge-request[\s\S]*flex: 1 1 auto/);
assert.match(script, /buildReviewSummaries/);
assert.match(script, /class="dm_forge-review-summary"/);
assert.match(script, /data-forge-panel="request"/);
assert.match(script, /data-forge-panel="review"/);
assert.match(script, /<span>Description<\/span>/);
assert.match(script, /<span>Result<\/span>/);
assert.match(styles, /\.dm_forge-pane-header/);
assert.match(styles, /\.dm_forge-provider-summary/);
assert.match(styles, /\.dm_forge-settings-shell \.form-header/);
assert.match(styles, /\.dm_forge-settings-intro-block[\s\S]*flex: 0 0 auto !important/);
assert.match(styles, /\.dm_forge-settings-shell > \.form-footer/);
assert.match(styles, /\.dm_forge-provider-settings[\s\S]*grid-template-columns: minmax\(0, 1fr\)/);
assert.match(settingsTemplate, /class="dm_forge-settings-intro-block"/);
assert.match(settingsTemplate, /class="dm_forge-provider-settings" data-provider-configuration/);
assert.match(script, /<details class="dm_forge-advanced">/);
assert.match(styles, /\.dm_forge-item-summary/);
assert.match(styles, /\.dm_forge-item-sheet-tabs/);
assert.match(styles, /\.dm_forge-bottom-tray/);
assert.match(script, /data-forge-notices/);
assert.match(script, /Report Failed Item/);
assert.match(script, /failedItemReportDialogContent/);
assert.match(script, /buildFailedItemReportPayload/);
assert.match(script, /data-action="report-failed-item"/);
assert.match(script, /_dm_forgeReviewValidated/);
assert.match(settingsTemplate, /name="providerEndpoint"/);
assert.match(settingsTemplate, /name="providerModel"/);
assert.match(settingsTemplate, /name="providerApiToken"/);
assert.match(settingsTemplate, /name="rememberProviderApiToken"/);
assert.match(settingsTemplate, /name="anonymousErrorReports"/);
assert.match(settingsTemplate, /data-action="example"/);
assert.match(settingsTemplate, /data-action="diagnostics"/);
assert.match(script, /providerSessionConfiguration/);
assert.match(script, /syncSettingsProviderPanel/);
assert.match(settingsTemplate, /data-action="check-provider"/);
assert.match(settingsTemplate, /type="submit" data-action="save-settings"/);
assert.match(settingsTemplate, /data-action="open-forge"/);
assert.match(script, /requestRemoteHealth/);
assert.match(script, /requestRemoteServiceStatus/);
assert.match(script, /Checking remote service status/);
assert.match(script, /providerConnectionDetailText/);
assert.match(script, /action: "settings"/);
assert.match(styles, /\.dungeon-masters-forge \.form-footer \[data-action="settings"\]/);
assert.match(script, /async function prepareSpecsForForge\(input, requestText = ""\)/);
assert.match(script, /function syncPreparedSpecs\(dialog, form, specs\)/);
assert.match(script, /const preparedCompilation = compilationWithPreparedSpecs\(compilation, validation\.specs\);/);
assert.match(script, /const preparedRawSpecs = syncPreparedSpecs\(dialog, button\.form, validation\.specs\);/);
assert.ok((script.match(/const specs = await prepareSpecsForForge\(input, requestText\);/g) ?? []).length >= 2);
assert.doesNotMatch(script, /dungeonMastersForgeSettings/);
assert.match(script, /const form = root instanceof HTMLFormElement \? root : root\?\.querySelector\?\.\("form"\)/);
assert.ok((script.match(/const form = root instanceof HTMLFormElement \? root : root\?\.querySelector\?\.\("form"\)/g) ?? []).length >= 3);
assert.match(script, /mock mode/);
assert.match(script, /game\.settings\.set\(MODULE_ID, "providerApiToken", rememberApiToken \? partitioned\.session\.apiToken : ""\)/);
assert.match(settingsTemplate, /Use only on a trusted computer/);
assert.match(script, /this\._dm_forgeProviderConnection = await checkProviderConnection\(providerState\);\s*await persistProviderState\(providerState\);/);
assert.match(script, /function applyHostedDefaultProvider\(\)/);
assert.match(script, /networkProviderConfiguration/);
assert.match(styles, /\.dm_forge-approval-box/);
assert.match(styles, /\.dm_forge-approval input:checked \+ \.dm_forge-approval-box/);
assert.match(script, /dm_forge-approval-compact/);
assert.match(styles, /\.dm_forge-report-action/);
assert.match(styles, /\.dm_forge-report-action-controls/);
assert.match(styles, /\.dm_forge-report-dialog/);
assert.match(script, /minimizable: true/);
assert.match(styles, /\.dm_forge-settings-shell > \.form-footer button[\s\S]*color: #f6ebe2/);
assert.match(forgeEngine, /function compactText\(value\)/);
assert.match(forgeEngine, /override: Boolean\(hasExplicitRange \|\| range\.override === true\)/);
assert.match(forgeEngine, /override: Boolean\(hasTemplate \|\| hasAffects \|\| target\.override === true\)/);
assert.match(forgeEngine, /function activityConsumption\(chargeCost = 1, scaling = \{\}\)[\s\S]*spellSlot: false/);
assert.match(forgeEngine, /function activityConsumptionNone\(\)[\s\S]*spellSlot: false/);
assert.doesNotMatch(script, /planningTier/);
assert.doesNotMatch(script, /tierReview/);
assert.doesNotMatch(settingsTemplate, /Planning tier/);

export const testedUsabilityContractCount = 81;
