const PATTERN_GUIDANCE = Object.freeze({
  weaponExtraDamage: "Magic weapon. Use weaponType, baseItem, properties, damage.base, damage.versatile, magicalBonus, range, extraDamageParts, and attackName.",
  weaponConditionOnHit: "Magic weapon with extraDamageParts and conditionOnHit. conditionOnHit includes condition, save ability/DC, duration seconds, and optional targetCreatureType such as undead when the request names a creature type. Keep the attack and condition rider together only for this family.",
  passiveEffectEquipment: "Passive worn item. Use equipmentType, effects with changes [{key, mode:'ADD'|'OVERRIDE'|'CUSTOM', value}], rarity, attunement, and description.",
  shieldArmorBonus: "Magic shield. Use armorValue 2, magicalBonus, baseItem:'shield', rarity, attunement, and description.",
  chargedHealing: "Healing consumable or charged item. Use itemType, consumableType when relevant, uses, activationType, healing, and autoDestroy for consumed items.",
  chargedSaveDamage: "One save/damage activity. Use uses, activityId, activationType, chargeCost, save {ability,dc}, damageParts, target, and halfOnSave. Thrown grenades, bombs, splash flasks, and similar one-use area projectiles belong here when their primary resolved mechanic is a single save-plus-damage activity.",
  multiActivityStaff: "Shared charge item with activities. Each activity has activityId, activityName, chargeCost, and target. Save powers use save plus optional damageParts; utility powers such as Misty Step or Dimension Door omit save/damageParts. Put recovery only on the shared uses object and preserve each named power as its own activity.",
  nativeEnchant: "One-use native enchantment. Oils, unguents, salves, coatings, and similar applied enchantments use this family. Use activityId, effectId, uses, duration, restrictions, and enchantChanges. Enchantment changes target the selected weapon or armor, not the oil itself.",
  nativeSummon: "One summon profile. Use activityId, profileId, uses, activationType, duration, range, target, and summonActor. Prefer a known DND5e SRD actor with srdActorName, but provide a basic declarative actor fallback {name,type,ac,hp} so the summon still works when that actor is unavailable.",
  nativeMultiProfileSummon: "Selectable summon profiles. Use summonActivity and summonProfiles; every profile has profileId, profileName, and actor. Prefer known DND5e SRD actor references, but provide basic declarative actor fallbacks {name,type,ac,hp} for every profile.",
  casterUtilityEquipment: "Caster item combining passive effects with known utility spell activities. Use effects, uses, utilityActivities, saveActivities when a spell has a save, and resistances through Active Effect changes.",
  equipmentPowerSuite: "Complex non-weapon equipment or consumable projectile. Use effects, uses, attackActivities, utilityActivities, saveActivities, summonActivity, and summonProfiles as needed. Keep each command as a separate activity. Thrown alchemical fire, acid flasks, and similar one-use attack consumables may use this family when they need a consumable chassis plus explicit attack activity.",
  legendaryEquipmentSuite: "Complex legendary non-weapon item. Use passive effects, shared charges, separate utility/save/attack/summon activities, and unresolved records for table-adjudicated clauses.",
  artifactWeaponHybrid: "Artifact weapon. Use normal weapon damage, optional extraDamageParts only for on-hit riders, passiveEffects, toggleLight, uses, utilityActivities, and separate saveActivities for activated spell damage. Never make activated spell damage part of every weapon attack."
});

const COMMON_GUIDANCE = `
Use DND5e v5.3.3-compatible values. Rarity values include common, uncommon, rare, veryRare, legendary, and artifact. Attunement is usually "" or "required". Damage parts use {number, denomination, bonus, types:[damageType]}. Uses use {max, recovery:[{period,type,formula?}], autoDestroy?}; consumed single-use items may use recovery:[] with autoDestroy:true. Saves use {ability, dc}. Ranges use {value, long?, units:'ft'}; areas use target.template with type and size. Effect changes use Foundry paths such as system.attributes.ac.bonus, system.bonuses.abilities.save, system.bonuses.mwak.attack, system.bonuses.rwak.attack, system.bonuses.mwak.damage, system.bonuses.rwak.damage, system.bonuses.msak.attack, system.bonuses.rsak.attack, system.attributes.spelldc, and system.traits.dr.value.

Every item must emit exactly one supported renderer kind. A renderer kind may compose mechanics from several historical families; preserve every advertised declarative capability and use a suite or hybrid renderer when needed. Every activityId, effectId, profileId, toggle-light ID, and unresolved-mechanic ID must be exactly 16 ASCII alphanumeric characters. The service will fill missing IDs, but never invent malformed ones. Separate attacks, healing, saves, utility powers, enchantments, and summons into distinct activities. Existing spells with a saving throw must use saveActivities even when they deal no damage. Oils, unguents, salves, and coatings that enchant a weapon, armor, or shield must use nativeEnchant instead of chargedSaveDamage. Throwable grenades, bombs, flasks, and vials are consumable projectile documents, not weapons; never add magicalBonus or attackBonus unless the request explicitly asks for that bonus. For summons, treat the named creature or descriptive role as a suggestion: prefer a matching DND5e SRD actor through summonActor.srdActorName or summonProfiles[].actor.srdActorName, but always include basic declarative fallback fields {name,type,ac,hp}. The Foundry renderer clones the SRD actor when found and otherwise creates the reviewed fallback actor. Never generate macros, scripts, or executable actor behavior. Unknown spells, ally auras, class-resource restoration, and table-judgment clauses become unresolvedMechanics instead of fake personal effects.

When the active Forge context advertises a supported automation recipe, you may emit an optional declarative automation object with recipe, trigger, workflowPass, targetSource, targetFilter, resourcePolicy, effectRecipe, duration, authority, idempotencyScope, fallback, and requires. Use only the advertised recipe and dependency values. This object describes a trusted local renderer path; it is not executable code. Never emit macroCommand, macroData, script, scripts, flags, eval, or arbitrary JavaScript.

For a self-only light toggle, emit toggleLight with target.affects.type set to self and target.prompt false; the trusted Foundry engine resolves the active source token and generates the reviewed toggle behavior. Do not describe this as a generic passive effect or emit a stale "light was not preserved" warning when the declarative toggleLight is present. For named multi-power staffs, rods, and wands, preserve every named power as a separate activity with its own chargeCost; utility powers omit save and damageParts, saving-throw powers use saveActivities, and unsupported teleport destinations remain visible manual-review findings.

For weaponConditionOnHit and artifactWeaponHybrid specs with conditionOnHit, the trusted Foundry renderer supplies the basic attack's default focused single-creature target and runs the save/effect rider from that same attack. If the request names a creature type, emit conditionOnHit.targetCreatureType and never apply the rider to a nonmatching target. Do not emit a workflow-verification or no-extra-target-dialog clause as unresolvedMechanics unless the request explicitly asks for a different targeting mode. Area templates may be declared on native activities, but do not promise automatic targeting of every token in a template unless the request and active module contract explicitly support it.

Each unresolved mechanic is {category,label,requestedText,reason,handling,resolved:false}. Preserve the exact requested clause in requestedText. Supported unresolved categories include allyAura, classResource, unmappedSpell, and tableAdjudication.
`;

function guidanceForKinds(kinds) {
  return kinds.map(kind => `- ${kind}: ${PATTERN_GUIDANCE[kind]}`).filter(line => !line.endsWith("undefined")).join("\n");
}

export { COMMON_GUIDANCE, PATTERN_GUIDANCE, guidanceForKinds };
